FROM node:16

WORKDIR /usr/src/app

COPY server/package*.json ./server/

RUN cd server && npm ci

COPY ./server server

EXPOSE 8080 8081

CMD cd server && ./node_modules/.bin/tsc && node build/index.js
