[http.middlewares.simpleAuth.basicAuth]
  users = [
    '{{env "BASIC_AUTH"}}'
  ]

[http.routers.api]
  rule = "Host(`{{env "HOST"}}`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
